### ISSUE TITLE
docker build fails using go v1.16 or above 

### ISSUE THREAD

**Issue by noandrea** [noandrea/geo2tz#5]
docker build fails using the golang docker image v1.16 or above. This seems to be due to a different way how the `go get` command operates. 
The `go get` command is used to download the timezone package to generate the timezone database. 

A solution could be to directly depend to the library instead of just using it at build time

**Comment by tsony-tsonev** [comment]
hm it is something related to the docker image bases, checkout https://stackoverflow.com/questions/57648290/golang-cannot-find-package-in-docker-image

**Comment by noandrea** [comment]
@tsony-tsonev the new version with memory shapefile support is ready. 
At the moment the docker image is at `github.com/noandrea/geo2tz:master`

**Comment by tsony-tsonev** [comment]
Hm im unable to build the dockerfile
```
 sudo docker build -t noandrea/geo2tz https://raw.githubusercontent.com/noandrea/geo2tz/master/Dockerfile
```
gives
```
Step 5/18 : RUN curl -LO https://github.com/evansiroky/timezone-boundary-builder/releases/download/2020d/timezones-with-oceans.geojson.zip
 ---> Using cache
 ---> 4330eddce4c4
Step 6/18 : RUN unzip timezones-with-oceans.geojson.zip
 ---> Using cache
 ---> e2d1ac968633
Step 7/18 : WORKDIR /builder
 ---> Using cache
 ---> c479688ded39
Step 8/18 : COPY . .
 ---> Using cache
 ---> 42e2c529418c
Step 9/18 : RUN go get -d -v
 ---> Running in eff0bebeeeaf
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
The command '/bin/sh -c go get -d -v' returned a non-zero code: 1
```

**Comment by noandrea** [comment]
thanks for reporting, should be fixed now.

here the latest docker  release https://github.com/noandrea/geo2tz/pkgs/container/geo2tz

if you still have problem, please reopen the issue

**Comment by tsony-tsonev** [comment]
I'm still unable to run the image with the memory shapefile:
```
sudo docker pull ghcr.io/noandrea/geo2tz:latest

latest: Pulling from noandrea/geo2tz
Digest: sha256:fcf44f1b35382f43c265827c10e917e1d00243e867e5660f0dea3ae8134643af
Status: Image is up to date for ghcr.io/noandrea/geo2tz:latest
ghcr.io/noandrea/geo2tz:latest
```

```
sudo docker run -it --mount type=bind,source=`pwd`/config.yaml,target=/etc/geo2tz/config.yaml -p 2004:2004 noandrea/geo2tz

 / ____|         |__ \| |
| |  __  ___  ___   ) | |_ ____
| | |_ |/ _ \/ _ \ / /| __|_  /
| |__| |  __/ (_) / /_| |_ / /
 \_____|\___|\___/____|\__/___| version 0.0.0
ERRO[0000] Error starting the server open timezone.snap.json: no such file or directory
```

with config.yaml

```
cat config.yaml

tz:
    database_type: memory
    database_name: timezone
    snappy: true
```

**Comment by tsony-tsonev** [comment]
I'm unable to reopen the issue

**Comment by noandrea** [comment]
https://github.com/noandrea/geo2tz/issues/6
